const $ = (selector) => document.querySelector(selector);
const labels = {software_engineering:"Software engineering",data_ai:"Data & AI",product:"Product",design:"Design",finance:"Finance",consulting:"Consulting",sales:"Sales",marketing:"Marketing",operations:"Operations",legal_policy:"Legal & policy",other:"Other"};
let viewer = null, allJobs = [];
async function api(path, options = {}) { const response = await fetch(`/api/poker${path}`, {headers:{"Content-Type":"application/json", ...(options.headers||{})}, ...options}); const data = await response.json().catch(()=>null); if (!response.ok) throw new Error(data?.error?.message || "Something went wrong."); return data; }
function setError(target, error = "") { $(target).textContent = error; }
function date(value) { return new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`)); }
function render() { const type = $("#type-filter").value; const jobs = allJobs.filter(job => type === "all" || job.jobType === type); $("#count").textContent = `${jobs.length} ${jobs.length === 1 ? "open role" : "open roles"}`; $("#jobs").innerHTML = jobs.length ? jobs.map(job => `<article class="job card"><button class="text-button delete" data-delete="${job.id}" ${viewer?.id === job.submittedByMemberId ? "" : "hidden"}>Remove</button><span class="badge">${labels[job.jobType]}</span><h3>${escapeHtml(job.title)}</h3><div class="company">${escapeHtml(job.company)}</div>${job.description ? `<p>${escapeHtml(job.description)}</p>` : ""}<div class="job-footer"><span>${job.applicationDeadline ? `Deadline: ${date(job.applicationDeadline)}` : "No deadline listed"}<br>Shared by ${escapeHtml(job.submittedBy)}</span><a class="apply" href="${escapeAttr(job.applicationUrl)}" target="_blank" rel="noopener noreferrer">Apply ↗</a></div></article>`).join("") : `<div class="empty card">No roles in this category yet. Be the first to share one.</div>`; }
function escapeHtml(value) { const el=document.createElement("div"); el.textContent=value; return el.innerHTML; }
function escapeAttr(value) { return escapeHtml(value).replace(/`/g,"&#96;"); }
async function load() { const data = await api("/jobs"); allJobs = data.jobs; render(); }
async function boot() { try { const status = await api("/auth/status"); viewer = status.viewer; if (!status.group) { $("#gate").hidden=false; return; } $("#logout").hidden=false; if (!viewer) { const data=await api("/members"); $("#member").innerHTML=`<option value="">Select your name</option>${data.members.map(member=>`<option value="${member.id}">${escapeHtml(member.name)}</option>`).join("")}`; $("#identity").hidden=false; return; } $("#board").hidden=false; await load(); } catch { $("#gate").hidden=false; } }
$("#login-form").addEventListener("submit", async event => { event.preventDefault(); setError("#login-error"); try { await api("/auth/login",{method:"POST",body:JSON.stringify({password:$("#password").value})}); await boot(); } catch(error) { setError("#login-error",error.message); } });
$("#identity-form").addEventListener("submit",async event=>{event.preventDefault();setError("#identity-error");try{const data=await api("/viewer",{method:"POST",body:JSON.stringify({memberId:$("#member").value})});viewer=data.viewer;$("#identity").hidden=true;$("#board").hidden=false;await load()}catch(error){setError("#identity-error",error.message)}});
$("#logout").addEventListener("click",async()=>{await api("/auth/logout",{method:"POST"}); location.reload();});
$("#show-form").addEventListener("click",()=>{ if (!viewer) { $("#notice").textContent="Choose your name in the Poker Ledger first, then come back to share a job."; return; } $("#job-form-card").hidden=false; $("#job-form-card").scrollIntoView({behavior:"smooth"}); });
$("#close-form").addEventListener("click",()=>$("#job-form-card").hidden=true);
$("#suggest").addEventListener("click",async()=>{ const input=$("[name=applicationUrl]"); setError("#form-error"); if (!input.value) return setError("#form-error","Add an application link first."); $("#suggest").disabled=true; $("#suggest").textContent="Checking…"; try { const data=await api("/jobs/suggest",{method:"POST",body:JSON.stringify({applicationUrl:input.value})}); if(data.category) $("[name=jobType]").value=data.category; if(data.applicationDeadline) $("[name=applicationDeadline]").value=data.applicationDeadline; $("#notice").textContent="Suggestion added—please verify it against the listing."; } catch(error) { setError("#form-error",error.message); } finally { $("#suggest").disabled=false; $("#suggest").textContent="Find deadline & type"; } });
$("#job-form").addEventListener("submit",async event=>{event.preventDefault();setError("#form-error");const form=new FormData(event.currentTarget);const body=Object.fromEntries(form.entries());if(!body.description) delete body.description;if(!body.applicationDeadline) delete body.applicationDeadline;$("#submit").disabled=true;try{await api("/jobs",{method:"POST",body:JSON.stringify(body)});event.currentTarget.reset();$("#job-form-card").hidden=true;$("#notice").textContent="Job posted to the 180 board.";await load();}catch(error){setError("#form-error",error.message)}finally{$("#submit").disabled=false}});
$("#type-filter").addEventListener("change",render);$("#jobs").addEventListener("click",async event=>{const button=event.target.closest("[data-delete]");if(!button||!confirm("Remove this job from the board?"))return;try{await api(`/jobs/${button.dataset.delete}`,{method:"DELETE"});await load()}catch(error){$("#notice").textContent=error.message}});boot();
